### PR TITLE
new release

### PR DESCRIPTION
**Pull request by mpmdean**
This is to aims to make and distribute a new release. @mrakitin if you could check this that would be great. 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@mpmdean, I don't see the version at https://pypi.org/project/edrixs/#history. Can you please push the source distribution there?

**Comment by mpmdean** [comment]
Hi @mrakitin 

When I try to upload via the instructions here
https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-releases.html

I get the error message

```
Binary wheel 'edrixs-0.0.8-cp36-cp36m-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'.
```

**Comment by mrakitin** [comment]
I think uploading sdist (.tar.gz) will be sufficient for now. I don't think we updated the setup.py to build the wheels correctly.

**Comment by mpmdean** [comment]
@mrakitin I just uploaded the .tar.gz only and verified it appears on pypi.

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Pull request merged**
